### ISSUE TITLE
TypeError: swc.vite is not a function

### ISSUE THREAD

**Issue by shlroland** [egoist/unplugin-swc#26]
error when starting dev server:
TypeError: swc.vite is not a function
    at file:///Users/shenhaoliang/Desktop/jgy/workbench/vite.config.ts.js?t=1649945077486:62:9
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/Users/shenhaoliang/Desktop/jgy/workbench/node_modules/vite/dist/node/chunks/dep-611778e0.js:61416:31)
    at async resolveConfig (/Users/shenhaoliang/Desktop/jgy/workbench/node_modules/vite/dist/node/chunks/dep-611778e0.js:60962:28)
    at async createServer (/Users/shenhaoliang/Desktop/jgy/workbench/node_modules/vite/dist/node/chunks/dep-611778e0.js:58813:20)
    at async CAC.<anonymous> (/Users/shenhaoliang/Desktop/jgy/workbench/node_modules/vite/dist/node/cli.js:688:24)

version: unplugin-swc 1.3.0

**Comment by shlroland** [comment]
> please provide a repro

That's because I set "type": "module" in package.json, so this plugin doesn;t support native esm?

**Comment by bestickley** [comment]
@shlroland, did the update in 1.3.2 work for you in an ESM package? While I can now import the function, I'm getting an error about dynamic use of require. See here: [Error: Dynamic require of "path" is not supported](https://github.com/egoist/unplugin-swc/issues/30)
