### ISSUE TITLE
parse worker error with this plugin 

### ISSUE THREAD

**Issue by WarrenXia** [egoist/unplugin-swc#4]
[vite:worker] Unexpected token (8:23)
file: D:/workspace/kdocs/@kso_image-viewer/src/preload/preload.worker.ts?worker&inline:8:23
SyntaxError: Unexpected token (8:23)
    at Parser.pp$5.raise (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:19547:13)
    at Parser.pp.unexpected (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:16872:8)
    at Parser.pp.expect (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:16866:26)
    at Parser.pp$4.parseParenAndDistinguishExpression (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:19008:36)
    at Parser.pp$4.parseExprAtom (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:18881:41)
    at Parser.pp$4.parseExprSubscripts (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:18714:19)
    at Parser.pp$4.parseMaybeUnary (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:18680:17)
    at Parser.pp$4.parseExprOps (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:18613:19)
    at Parser.pp$4.parseMaybeConditional (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:18596:19)
    at Parser.pp$4.parseMaybeAssign (D:\workspace\kdocs\@kso_image-viewer\node_modules\rollup\dist\shared\rollup.js:18564:19)

**Comment by egoist** [comment]
Please provide a repro.
